In [1]:
#importing the modules
import os
import pandas as pd
import numpy as np

from pathlib import Path

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 200)

In [3]:
#inspecting the all available data
DATA_DIR = Path(r"C:\Users\HP\OneDrive\Desktop\BPUT\CYBERGUARD\phishing_detection\data")

print("Data directory:", DATA_DIR.resolve())
print("\nFiles found:")

for file in DATA_DIR.iterdir():
    print(file.name)
files = list(DATA_DIR.glob("*"))

for i, file in enumerate(files, start=1):
    print(f"{i}. {file.name}")

Data directory: C:\Users\HP\OneDrive\Desktop\BPUT\CYBERGUARD\phishing_detection\data

Files found:
CEAS_08.csv
Enron.csv
Ling.csv
Nazario.csv
Nigerian_Fraud.csv
phishing_email.csv
SpamAssasin.csv
1. CEAS_08.csv
2. Enron.csv
3. Ling.csv
4. Nazario.csv
5. Nigerian_Fraud.csv
6. phishing_email.csv
7. SpamAssasin.csv

In [5]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path("../data")

dataset_files = [
    "CEAS_08.csv",
    "Enron.csv",
    "Ling.csv",
    "Nazario.csv",
    "Nigerian_Fraud.csv",
    "phishing_email.csv",
    "SpamAssasin.csv"
]

datasets = {}

for filename in dataset_files:
    path = DATA_DIR / filename
    
    try:
        df = pd.read_csv(path)
        datasets[filename] = df
        
        print("=" * 80)
        print(f"DATASET: {filename}")
        print(f"Shape: {df.shape}")
        print(f"Columns: {df.columns.tolist()}")
        print()
        print(df.head(2))
        print()
        
    except Exception as e:
        print(f"ERROR loading {filename}: {e}")

================================================================================
DATASET: CEAS_08.csv
Shape: (39154, 7)
Columns: ['sender', 'receiver', 'date', 'subject', 'body', 'label', 'urls']

                             sender                       receiver  \
0  Young Esposito <Young@iworld.de>    user4@gvc.ceas-challenge.cc
1      Mok <ipline's1983@icable.ph>  user2.2@gvc.ceas-challenge.cc

                              date                    subject  \
0  Tue, 05 Aug 2008 16:31:02 -0700  Never agree to be a loser
1  Tue, 05 Aug 2008 18:31:03 -0500     Befriend Jenna Jameson

                                                                                                                                                                                                      body  \
0  Buck up, your troubles caused by small dimension will soon be over!\nBecome a lover no woman will be able to resist!\nhttp://whitedone.com/\n\n\ncome. Even as Nazi tanks were rolling down the stre...
1                                                                                                                   \nUpgrade your sex and pleasures with these techniques http://www.brightmade.com\n\n\n

   label  urls
0      1     1
1      1     1

================================================================================
DATASET: Enron.csv
Shape: (29767, 3)
Columns: ['subject', 'body', 'label']

                            subject  \
0         hpl nom for may 25 , 2001
1  re : nom / actual vols for 24 th

                                                                                                                                                                                                      body  \
0                                                                                                                                             ( see attached file : hplno 525 . xls )\r\n- hplno 525 . xls
1  - - - - - - - - - - - - - - - - - - - - - - forwarded by sabrae zajac / hou / ect on 05 / 30 / 2001 12 : 07 pm - - - - - - - - - - - - - - - - - - - - - - - - - - -\r\nenron capital & trade resour...

   label
0      0
1      0

================================================================================
DATASET: Ling.csv
Shape: (2859, 3)
Columns: ['subject', 'body', 'label']

                                   subject  \
0  job posting - apple-iss research center
1                                      NaN

                                                                                                                                                                                                      body  \
0  content - length : 3386 apple-iss research center a us $ 10 million joint venture between apple computer inc . and the institute of systems science of the national university of singapore , locate...
1  lang classification grimes , joseph e . and barbara f . grimes ; ethnologue language family index ; pb . isbn : 0-88312 - 708 - 3 ; vi , 116 pp . ; $ 14 . 00 . summer institute of linguistics . th...

   label
0      0
1      0

================================================================================
DATASET: Nazario.csv
Shape: (1565, 7)
Columns: ['sender', 'receiver', 'date', 'subject', 'body', 'urls', 'label']

                                                 sender         receiver  \
0  Mail System Internal Data <MAILER-DAEMON@monkey.org>              NaN
1                           cPanel <service@cpanel.com>  jose@monkey.org

                              date  \
0       28 Sep 2017 09:57:25 -0400
1  Fri, 30 Oct 2015 00:00:48 -0500

                                             subject  \
0  DON'T DELETE THIS MESSAGE -- FOLDER INTERNAL DATA
1                                Verify Your Account

                                                                                                                                                                                                      body  \
0  This text is part of the internal format of your mail folder, and is not a real message.  It is created automatically by the mail system software. If deleted, important folder data will be lost, a...
1  Business with  \t\t\t\t\t\t\t\tcPanel & WHM \t\t\t\t\t\t\t\tDear client, Our Technical  \t\t\t\t\t\t\t\tServices Department are carrying out a planned  \t\t\t\t\t\t\t\tsoftware upgrade. Please log...

   urls  label
0     1      1
1     1      1

================================================================================
DATASET: Nigerian_Fraud.csv
Shape: (3332, 7)
Columns: ['sender', 'receiver', 'date', 'subject', 'body', 'urls', 'label']

                                           sender              receiver  \
0  MR. JAMES NGOLA. <james_ngola2002@maktoob.com>  webmaster@aclweb.org
1  Mr. Ben Suleman <bensul2004nng@spinfinder.com>                   R@M

                              date  \
0  Thu, 31 Oct 2002 02:38:20 +0000
1  Thu, 31 Oct 2002 05:10:00 -0000

                                      subject  \
0  URGENT BUSINESS ASSISTANCE AND PARTNERSHIP
1         URGENT ASSISTANCE /RELATIONSHIP (P)

                                                                                                                                                                                                      body  \
0  FROM:MR. JAMES NGOLA.\nCONFIDENTIAL TEL: 233-27-587908.\nE-MAIL: (james_ngola2002@maktoob.com).\n\nURGENT BUSINESS ASSISTANCE AND PARTNERSHIP.\n\n\nDEAR FRIEND,\n\nI AM ( DR.) JAMES NGOLA, THE PER...
1  Dear Friend,\n\nI am Mr. Ben Suleman a custom officer and work as Assistant controller of the Customs and Excise department Of the Federal Ministry of Internal Affairs stationed at the Murtala Moh...

   urls  label
0     0      1
1     0      1

================================================================================
DATASET: phishing_email.csv
Shape: (82486, 2)
Columns: ['text_combined', 'label']

                                                                                                                                                                                             text_combined  \
0                                                                                                                                        hpl nom may 25 2001 see attached file hplno 525 xls hplno 525 xls
1  nom actual vols 24 th forwarded sabrae zajac hou ect 05 30 2001 12 07 pm enron capital trade resources corp eileen ponton 05 29 2001 08 37 davilal txu com cstonel txu com mjones 7 txu com hpl sche...

   label
0      0
1      0

================================================================================
DATASET: SpamAssasin.csv
Shape: (5809, 7)
Columns: ['sender', 'receiver', 'date', 'subject', 'body', 'label', 'urls']

                                      sender  \
0             Robert Elz <kre@munnari.OZ.AU>
1  Steve Burt <Steve_Burt@cursor-system.com>

                                                     receiver  \
0  Chris Garrigues <cwg-dated-1030377287.06fa6d@DeepEddy.Com>
1   "'zzzzteana@yahoogroups.com'" <zzzzteana@yahoogroups.com>

                              date                    subject  \
0  Thu, 22 Aug 2002 18:26:25 +0700   Re: New Sequences Window
1  Thu, 22 Aug 2002 12:46:18 +0100  [zzzzteana] RE: Alexander

                                                                                                                                                                                                      body  \
0  Date:        Wed, 21 Aug 2002 10:54:46 -0500     From:        Chris Garrigues      Message-ID:  <1029945287.4797.TMDA@deepeddy.vircio.com>   | I can't reproduce this error. For me it is very repea...
1  Martin A posted:\nTassos Papadopoulos, the Greek sculptor behind the plan, judged that the\n limestone of Mount Kerdylio, 70 miles east of Salonika and not far from the\n Mount Athos monastic comm...

   label  urls
0      0     1
1      0     1

In [6]:
#inspecting the labels
for name, df in datasets.items():
    print("=" * 80)
    print(f"{name}")
    
    print("\nColumns:")
    print(df.columns.tolist())
    
    print("\nPossible label columns:")
    for col in df.columns:
        unique_count = df[col].nunique(dropna=False)
        
        if unique_count <= 10:
            print(f"  {col}: {unique_count} unique values")
            print(f"     {df[col].value_counts(dropna=False).to_dict()}")

================================================================================
CEAS_08.csv

Columns:
['sender', 'receiver', 'date', 'subject', 'body', 'label', 'urls']

Possible label columns:
  label: 2 unique values
     {1: 21842, 0: 17312}
  urls: 2 unique values
     {1: 26232, 0: 12922}
================================================================================
Enron.csv

Columns:
['subject', 'body', 'label']

Possible label columns:
  label: 2 unique values
     {0: 15791, 1: 13976}
================================================================================
Ling.csv

Columns:
['subject', 'body', 'label']

Possible label columns:
  label: 2 unique values
     {0: 2401, 1: 458}
================================================================================
Nazario.csv

Columns:
['sender', 'receiver', 'date', 'subject', 'body', 'urls', 'label']

Possible label columns:
  urls: 2 unique values
     {1: 1423, 0: 142}
  label: 1 unique values
     {1: 1565}
================================================================================
Nigerian_Fraud.csv

Columns:
['sender', 'receiver', 'date', 'subject', 'body', 'urls', 'label']

Possible label columns:
  urls: 2 unique values
     {0: 2183, 1: 1149}
  label: 1 unique values
     {1: 3332}
================================================================================
phishing_email.csv

Columns:
['text_combined', 'label']

Possible label columns:
  label: 2 unique values
     {1: 42891, 0: 39595}
================================================================================
SpamAssasin.csv

Columns:
['sender', 'receiver', 'date', 'subject', 'body', 'label', 'urls']

Possible label columns:
  label: 2 unique values
     {0: 4091, 1: 1718}
  urls: 2 unique values
     {1: 5002, 0: 807}

In [7]:
#Investigating the label semantics
for name, df in datasets.items():
    print("=" * 80)
    print(name)
    
    if "label" in df.columns:
        for label in sorted(df["label"].dropna().unique()):
            sample = df[df["label"] == label]
            
            print(f"\nLABEL: {label}")
            print(f"Number of samples: {len(sample)}")
            
            cols = [c for c in ["subject", "body", "text_combined"] if c in df.columns]
            
            if cols:
                display(sample[cols].head(3))

================================================================================
CEAS_08.csv

LABEL: 0
Number of samples: 17312

,subject,body
3,Re: svn commit: r619753 - in /spamassassin/trunk: lib/Mail/SpamAssassin/PerMsgStatus.pm lib/Mail/SpamAssassin/Util/RegistrarBoundaries.pm t/uri_text.t,Would anyone object to removing .so from this list? The .so TLD is \nbasically dead and we've found that lots of bogus domains like lib*.so \nare being caught by this. Also sometimes you'll ha...
8,[Bug 5780] URI processing turns uuencoded strings into http URI's which then causes FPs,http://issues.apache.org/SpamAssassin/show_bug.cgi?id=5780\n\n\nwrzzpv@sidney.com changed:\n\n What |Removed |Added\n----------------------------------------------...
15,RE: Trial IRC Certificate Application,"\nPlelim,\n\nJust to remind you that if a certificate is needed in a hurry it can be expedited. This process is double the cost of a normal application. The normal cost for a Trial Certificate is ..."

LABEL: 1
Number of samples: 21842

,subject,body
0,Never agree to be a loser,"Buck up, your troubles caused by small dimension will soon be over!\nBecome a lover no woman will be able to resist!\nhttp://whitedone.com/\n\n\ncome. Even as Nazi tanks were rolling down the stre..."
1,Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these techniques http://www.brightmade.com\n\n\n
2,CNN.com Daily Top 10,">+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+= >THE DAILY TOP 10 >from CNN.com >Top videos and stories as of: Aug 1, 2008 3:58 PM EDT >+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=..."

================================================================================
Enron.csv

LABEL: 0
Number of samples: 15791

,subject,body
0,"hpl nom for may 25 , 2001",( see attached file : hplno 525 . xls )\r\n- hplno 525 . xls
1,re : nom / actual vols for 24 th,- - - - - - - - - - - - - - - - - - - - - - forwarded by sabrae zajac / hou / ect on 05 / 30 / 2001 12 : 07 pm - - - - - - - - - - - - - - - - - - - - - - - - - - -\r\nenron capital & trade resour...
2,"enron actuals for march 30 - april 1 , 201","estimated actuals\r\nmarch 30 , 2001\r\nno flow\r\nmarch 31 , 2001\r\nno flow\r\napril 1 , 2001\r\nteco tap 35 . 000\r\nwhen i receive the actuals from duke i will forward them to you ."

LABEL: 1
Number of samples: 13976

,subject,body
3501,d - link dwl - g 510 802 . 11 g wireless pci lan adapter @ $ 39 . 85,"$ 39 . 85 dwl - g 510\r\nhigh speed\r\n2 . 4\r\nghz ( 802 . 11 g ) wireless pci lan\r\nadapter\r\nieee 802 . 11 g standardupto\r\n54 mbpsoperating frequency range - 2 . 4\r\nghz "" is an ideal solu..."
3502,"indemand payperview movies , sports and more","wed , 15 sep 2004 11 : 33 : 14 + 0500\r\nhi cable tv subscriber\r\nthese per - per - view filters lets you get your pay - per - view , mature channels , movie channels , and sporting events for no..."
3503,want to lose up to 19 % weight . try adipren !,"hello , here ' s a special offer for you . . .\r\nyou want to lose weight ?\r\nthe most powerful weightloss is now available\r\nwithout prescription . all natural adipren\r\n100 % money back guara..."

================================================================================
Ling.csv

LABEL: 0
Number of samples: 2401

,subject,body
0,job posting - apple-iss research center,"content - length : 3386 apple-iss research center a us $ 10 million joint venture between apple computer inc . and the institute of systems science of the national university of singapore , locate..."
1,NaN,"lang classification grimes , joseph e . and barbara f . grimes ; ethnologue language family index ; pb . isbn : 0-88312 - 708 - 3 ; vi , 116 pp . ; $ 14 . 00 . summer institute of linguistics . th..."
2,query : letter frequencies for text identification,"i am posting this inquiry for sergei atamas ( satamas @ umabnet . ab . umd . edu ) , a research associate at the university of maryland at baltimore . his field is molecular biology , and his work..."

LABEL: 1
Number of samples: 458

,subject,body
21,free,"this is a multi-part message in mime format . - - - - - - = _ nextpart _ 000 _ 0139 _ 01bd8356 . 354ff2e0 content - type : multipart / alternative ; boundary = "" - - - - = _ nextpart _ 001 _ 013a ..."
38,the internet success toolbox,note : we do not wish to send e-mail to anyone that does not want it so please send an e-mail to : remove929 @ yahoo . com you will be removed promptly . * * * * * * * * * * * * * * * * * * * * * ...
84,free stealth 3 . 0 bulk email software . . .,"just released . . . 30 , 000 , 000 email addresses ! plus 12 bonuses . . . including free stealth 3 . 0 bulk email software these addresses are less than 21 days old . earn insane profits with the..."

================================================================================
Nazario.csv

LABEL: 1
Number of samples: 1565

,subject,body
0,DON'T DELETE THIS MESSAGE -- FOLDER INTERNAL DATA,"This text is part of the internal format of your mail folder, and is not a real message. It is created automatically by the mail system software. If deleted, important folder data will be lost, a..."
1,Verify Your Account,"Business with \t\t\t\t\t\t\t\tcPanel & WHM \t\t\t\t\t\t\t\tDear client, Our Technical \t\t\t\t\t\t\t\tServices Department are carrying out a planned \t\t\t\t\t\t\t\tsoftware upgrade. Please log..."
2,Helpdesk Mailbox Alert!!!,"Your two incoming mails were placed on pending status due to the recent upgrade in our database, In order to receive the messages kindly click: HERE Login with your correct Webmail information's a..."

================================================================================
Nigerian_Fraud.csv

LABEL: 1
Number of samples: 3332

,subject,body
0,URGENT BUSINESS ASSISTANCE AND PARTNERSHIP,"FROM:MR. JAMES NGOLA.\nCONFIDENTIAL TEL: 233-27-587908.\nE-MAIL: (james_ngola2002@maktoob.com).\n\nURGENT BUSINESS ASSISTANCE AND PARTNERSHIP.\n\n\nDEAR FRIEND,\n\nI AM ( DR.) JAMES NGOLA, THE PER..."
1,URGENT ASSISTANCE /RELATIONSHIP (P),"Dear Friend,\n\nI am Mr. Ben Suleman a custom officer and work as Assistant controller of the Customs and Excise department Of the Federal Ministry of Internal Affairs stationed at the Murtala Moh..."
2,GOOD DAY TO YOU,"FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF ELEME KINGDOM \nCHIEF DANIEL ELEME, PHD, EZE 1 OF ELEME.E-MAIL \nADDRESS:obong_715@epatra.com \n\nATTENTION:PRESIDENT,CEO Sir/ Madam. \n\nThis letter m..."

================================================================================
phishing_email.csv

LABEL: 0
Number of samples: 39595

                                                                                                                                                                                             text_combined
0                                                                                                                                        hpl nom may 25 2001 see attached file hplno 525 xls hplno 525 xls
1  nom actual vols 24 th forwarded sabrae zajac hou ect 05 30 2001 12 07 pm enron capital trade resources corp eileen ponton 05 29 2001 08 37 davilal txu com cstonel txu com mjones 7 txu com hpl sche...
2                                                     enron actuals march 30 april 1 201 estimated actuals march 30 2001 flow march 31 2001 flow april 1 2001 teco tap 35 000 receive actuals duke forward

LABEL: 1
Number of samples: 42891

                                                                                                                                                                                                text_combined
3503  link dwl g 510 802 11 g wireless pci lan adapter 39 85 39 85 dwl g 510 high speed 2 4 ghz 802 11 g wireless pci lan adapter ieee 802 11 g standardupto 54 mbpsoperating frequency range 2 4 ghz idea...
3504  indemand payperview movies sports wed 15 sep 2004 11 33 14 0500 hi cable tv subscriber per per view filters lets get pay per view mature channels movie channels sporting events nothing country gam...
3505  want lose 19 weight try adipren hello special offer want lose weight powerful weightloss available without prescription natural adipren 100 money back guarantee lose 19 total body weight loss 20 3...

================================================================================
SpamAssasin.csv

LABEL: 0
Number of samples: 4091

,subject,body
0,Re: New Sequences Window,"Date: Wed, 21 Aug 2002 10:54:46 -0500 From: Chris Garrigues Message-ID: <1029945287.4797.TMDA@deepeddy.vircio.com> | I can't reproduce this error. For me it is very repea..."
1,[zzzzteana] RE: Alexander,"Martin A posted:\nTassos Papadopoulos, the Greek sculptor behind the plan, judged that the\n limestone of Mount Kerdylio, 70 miles east of Salonika and not far from the\n Mount Athos monastic comm..."
2,[zzzzteana] Moscow bomber,"Man Threatens Explosion In Moscow \n\nThursday August 22, 2002 1:40 PM\nMOSCOW (AP) - Security officers on Thursday seized an unidentified man who\nsaid he was armed with explosives and threatened..."

LABEL: 1
Number of samples: 1718

,subject,body
4091,Life Insurance - Why Pay More?,* * * --- * * * <= /TR> Save up to 70% on Life Insurance. Why Spend More Than You Have To? Life Quote Savings __** _**__ **Ensurin= g your family's financial security is very i...
4092,[ILUG] Guaranteed to lose 10-12 lbs in 30 days 10.206,1) Fight The Risk of Cancer!\nhttp://www.adclick.ws/p.cfm?o=315&s=pk007\n\n2) Slim Down - Guaranteed to lose 10-12 lbs in 30 days\nhttp://www.adclick.ws/p.cfm?o=249&s=pk007\n\n3) Get the Child Sup...
4093,Guaranteed to lose 10-12 lbs in 30 days 11.150,1) Fight The Risk of Cancer!\nhttp://www.adclick.ws/p.cfm?o=315&s=pk007\n\n2) Slim Down - Guaranteed to lose 10-12 lbs in 30 days\nhttp://www.adclick.ws/p.cfm?o=249&s=pk007\n\n3) Get the Child Sup...

In [8]:
#checking the overlap and duplicacy in the dataset
for name, df in datasets.items():
    if "body" in df.columns:
        print(name, "body duplicates:", df["body"].duplicated().sum())

    if "text_combined" in df.columns:
        print(name, "text duplicates:", df["text_combined"].duplicated().sum())

CEAS_08.csv body duplicates: 0
Enron.csv body duplicates: 0
Ling.csv body duplicates: 0
Nazario.csv body duplicates: 0
Nigerian_Fraud.csv body duplicates: 0
phishing_email.csv text duplicates: 408
SpamAssasin.csv body duplicates: 0

In [9]:
# Create normalized text for overlap checking

def normalize_text(text):
    if pd.isna(text):
        return ""
    
    text = str(text).lower()
    text = " ".join(text.split())
    return text


# Create normalized body/text for each dataset
normalized_texts = {}

for name, df in datasets.items():
    
    if "text_combined" in df.columns:
        normalized_texts[name] = set(
            df["text_combined"].dropna().map(normalize_text)
        )
        
    elif "body" in df.columns:
        normalized_texts[name] = set(
            df["body"].dropna().map(normalize_text)
        )


# Compare phishing_email.csv against every other dataset
phishing_texts = normalized_texts["phishing_email.csv"]

print("phishing_email unique texts:", len(phishing_texts))
print()

for name, texts in normalized_texts.items():
    
    if name == "phishing_email.csv":
        continue
    
    overlap = phishing_texts.intersection(texts)
    
    print(f"{name}: {len(overlap):,} overlapping messages")

phishing_email unique texts: 82078

CEAS_08.csv: 0 overlapping messages
Enron.csv: 3 overlapping messages
Ling.csv: 0 overlapping messages
Nazario.csv: 1 overlapping messages
Nigerian_Fraud.csv: 1 overlapping messages
SpamAssasin.csv: 1 overlapping messages

In [10]:
#inspecting the actual label distribution and characteristics of phishing_email.csv
df = datasets["phishing_email.csv"]

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nLabel distribution:")
print(df["label"].value_counts())

print("\nLabel percentages:")
print(df["label"].value_counts(normalize=True) * 100)

print("\nSample messages by label:")

for label in sorted(df["label"].unique()):
    print(f"\n===== LABEL {label} =====")
    samples = df[df["label"] == label]["text_combined"].dropna().sample(
        min(10, len(df[df["label"] == label])),
        random_state=42
    )

    for i, text in enumerate(samples, 1):
        print(f"\n--- Example {i} ---")
        print(str(text)[:500])

Shape: (82486, 2)

Columns:
['text_combined', 'label']

Label distribution:
label
1    42891
0    39595
Name: count, dtype: int64

Label percentages:
label
1    51.997915
0    48.002085
Name: proportion, dtype: float64

Sample messages by label:

===== LABEL 0 =====

--- Example 1 ---
ned deily riyacmorg article 51951867168434095nz5d8bhudamiredorg mike meyer wrote thu 28 feb 2008 234249 0000 utc medhat gayed wrote lxml good written python difficult install didnt work macos x lxml built top libxml2libxslt bundled unixlike oss including mac os x available package systems trying install repository pita uses easyinstall pyrex later cython packages arent bundled anything hand package system longer macports installed anywhere believe one time solves problems believe theyve excised

--- Example 2 ---
perl jobs xycnvtnhzperlorg online url job httpjobsperlorgjob7990 subscribe list send mail jobssubscribeperlorg unsubscribe send mail jobsunsubscribeperlorg posted february 21 2008 job title front end web developer company name ticketmaster location ca west hollywodd pay rate market travel 0 terms employment salaried employee length employment fulltlime hours full time description ticketmaster looking frontend web developersoftware engineer join client tools team developing ajax point sale applic

--- Example 3 ---
model 04 28 good morning bill 4 28 could move 100 bookouts 5 6 6 00 top direct bill cuts psco deals keeping together also today end month probably checking amy kelley replacement houston wed thurs need models corrected thanks kathy

--- Example 4 ---
request historical curve information sure already taking care thanks paulo issler vince j kaminski 11 15 2000 09 59 paulo issler hou ect ect cc subject request historical curve information paulo please help vince forwarded vince j kaminski hou ect 11 15 2000 10 06 enron north america corp mike barry enron 11 15 2000 07 55 vince j kaminski hou ect ect cc subject request historical curve information vince per conversation morning would appreciate following historical curve information soon possibl

--- Example 5 ---
ted leung wxvrjpezsuncom communityone free open developer conference run sun day javaone year space communityone dedicated python community complete whiteboards wifi bay area javaone bay area plain interested python please register communityone space limited registering communityone gets bag swag free lunch day communityone access communityone events sessions free pass day 1 javaone register put pythonjython referral code url register panel community models general session 930am 1045am frank wie

--- Example 6 ---
history linguistic grammatical praxis ankuendigung einladung call papers xi internationales kolloquium des sgds mit dem schwerpunktthema geschichte der sprachwissenschaftlichen und grammati kographi schen praxis history linguistic grammatical praxis histoire de la praxis linguistique et grammaticale veranstaltet vom studienkreis geschichte der sprachwissenschaft sgds verbindung mit dem departement linguistiek der katholieke universiteit leuven leuven louvain b 02 04 07 1998 hinweis bei dem g the

--- Example 7 ---
2 882 np np much restrictive np np np pro quite overrestriction

--- Example 8 ---
peter desain zbfllunicirunl please find attached open postdoc position exciting new project bci als patients would appreciate help give getting highly qualified candidates best regards peter desain postdoc position classification bci online interpretation imagined temporal patterns eeg next step toward neuronal control motor communication processes recent studies shown imagery patterns time auditory sequences motor behavior gives rise almost pattern neuronal activity central nervous system actua

--- Example 9 ---
gregory p smith amuhkryptoorg trying update bug get fri may 2 071717 2008 error occurred please check server log infomation fri 08 aug 2008 005038 0700 pythondev tracker issues server error

--- Example 10 ---
ian andrew bell pnmqgianbellcom 24oct07 1244 pm dave long wrote usaian tell truth dont really ever think canada wait til run natural resources well think ever seen nhl well make kandahar look like disneyland ian wed 06 aug 2008 184157 0700 fork papers order federal govt require prior permission flight

===== LABEL 1 =====

--- Example 1 ---
angel guerra dwtheballoonroommtheballoonroomnet pe bj nis en dh large xig ment work order top pen tu patches wed 06 aug 2008 054833 0200 angel guerra

--- Example 2 ---
mrs aisha mohammed aishamohmshecom frommrs mohammed attnthe managing director proceed may humbly introduce goodself name mrs aisha mohammed iraqi refugee husband recently one personal aid president iraq formerly overthrown power prior last serious crisis still ravaging countrywhich recently led misfortune government late husband position personal aid president inherited sum us11 millionthe funds originally gotten late husband proceeds late husband able safe guard fund good diplomatic contact cou

--- Example 3 ---
cnn alerts afurak1977renimusiccom cnn alerts custom alert alert name custom alert dark knight kills mummy box office fri 8 aug 2008 160316 0800 full story agreed receive email cnncom result cnncom preference settings manage settings click alter alert criteria frequency unsubscribe receiving custom email alerts click cable news network one cnn center atlanta georgia 30303 2008 cable news network time warner company rights reserved view privacy policy terms fri 08 aug 2008 043832 0400 cnn alerts c

--- Example 4 ---
monkeyorg vicinfinitextilcom  10 dec 2019 084302 0000 utf8b0jlqsngiinc0l7rh9gc0l7qstgl0lkg0yridc40logjosemonkeyorg utf8b0ljrgdgc0lxqutcw0lxrgidrgdc10lpqvtc00l3rjywg0l7qsdc90l7qstc40ylqtsdqsdc10yhqv9c70ldrgtc90l4g0yhqtdc50yfqsngb

--- Example 5 ---
hallee know smurfette wished guy bigger mushroom httpwwwfiftydaycom using operas revolutionary email client httpwwwoperacommail tue 05 aug 2008 235051 0400 nurses flaming hot

--- Example 6 ---
connie godfrey cindyklystronlyonbeyondunrealcom abduct talkative annoyance gabriel hymn hymn econometric gabriel nudge plague radiology drive prevention bonaparte loamy nudge radiology nudge yogurt talkative sleep playful quiescent plague nudge yogurt annoyance quiescent herd loamy keller gesticulate rowdy narcissist econometric yogurt outlawry exclamation outlawry loamy rowdy prevention sleep acm roberts nudge rowdy playful playful unicorn thu 07 aug 2008 031554 0500 drive women narcissist rowd

--- Example 7 ---
40 sf valium charset iso 8859 7 offshore pharmacy questions super viagra cialis dubbed weekend pill longer life 36 hours compared 4 hours viagra acts faster little 15 minutes compared 60 minutes viagra best sex ever solid erection whenever need cialis control cialis works 15 minutes lasts 36 hours giving strong healthy erections whenever want need questions pay ship complete privacy confidentiatlity 128 bit encrypted website maximum security also assortment drugs soma valium xanax meridia etc so

--- Example 8 ---
daily top 10 atonnons_1996piromagru daily top 10 cnncom top videos stories aug 1 2008 358 pm edt top 10 videos 1 paris hilton takes mccain httpwwwcnncomvideopartnersemailindexhtmlurlvideopolitics20080806wynterparishiltonadcnn paris hilton swings back republican presidential candidate john mccain kareen wynter reports 2 bikini barista stand closed httpwwwcnncomvideopartnersemailindexhtmlurlvideoliving20080806pkgbikinibaristasbarredkiro 3 tot grandma reacts charges httpwwwcnncomvideopartnersemaili

--- Example 9 ---
nancy dailey akstcacadienouvellemnsdgsacadienouvellecom exclusive rx alternatives httpanythingwantedspaceslivecomdefaultaspx used java api brain works using amely chicago tue 05 aug 2008 234342 0500 perfected medicinal options

--- Example 10 ---
daily top 10 mmailise_1964jmkrealtycom daily top 10 cnncom top videos stories aug 1 2008 358 pm edt top 10 videos 1 mom parties club httpwwwcnncomvideopartnersemailindexhtmlurlvideocrime20080805ngmompicscnn nancy grace new photos casey anthony partying nightclub daughter caylee vanished 2 womans computer spies httpwwwcnncomvideopartnersemailindexhtmlurlvideotech20080805pkgwebcamspyingwcjb 3 tigers attack teen zoo httpwwwcnncomvideopartnersemailindexhtmlurlvideous20080805wuellnertigerattacksteenk

In [11]:
#all dataset labels check
for name, df in datasets.items():

    print("\n" + "=" * 70)
    print(name)

    print("Shape:", df.shape)

    print("\nLabels:")
    print(df["label"].value_counts())

    print("\nLabel percentages:")
    print((df["label"].value_counts(normalize=True) * 100).round(2))

    print("\nColumns:")
    print(df.columns.tolist())

======================================================================
CEAS_08.csv
Shape: (39154, 7)

Labels:
label
1    21842
0    17312
Name: count, dtype: int64

Label percentages:
label
1    55.78
0    44.22
Name: proportion, dtype: float64

Columns:
['sender', 'receiver', 'date', 'subject', 'body', 'label', 'urls']

======================================================================
Enron.csv
Shape: (29767, 3)

Labels:
label
0    15791
1    13976
Name: count, dtype: int64

Label percentages:
label
0    53.05
1    46.95
Name: proportion, dtype: float64

Columns:
['subject', 'body', 'label']

======================================================================
Ling.csv
Shape: (2859, 3)

Labels:
label
0    2401
1     458
Name: count, dtype: int64

Label percentages:
label
0    83.98
1    16.02
Name: proportion, dtype: float64

Columns:
['subject', 'body', 'label']

======================================================================
Nazario.csv
Shape: (1565, 7)

Labels:
label
1    1565
Name: count, dtype: int64

Label percentages:
label
1    100.0
Name: proportion, dtype: float64

Columns:
['sender', 'receiver', 'date', 'subject', 'body', 'urls', 'label']

======================================================================
Nigerian_Fraud.csv
Shape: (3332, 7)

Labels:
label
1    3332
Name: count, dtype: int64

Label percentages:
label
1    100.0
Name: proportion, dtype: float64

Columns:
['sender', 'receiver', 'date', 'subject', 'body', 'urls', 'label']

======================================================================
phishing_email.csv
Shape: (82486, 2)

Labels:
label
1    42891
0    39595
Name: count, dtype: int64

Label percentages:
label
1    52.0
0    48.0
Name: proportion, dtype: float64

Columns:
['text_combined', 'label']

======================================================================
SpamAssasin.csv
Shape: (5809, 7)

Labels:
label
0    4091
1    1718
Name: count, dtype: int64

Label percentages:
label
0    70.43
1    29.57
Name: proportion, dtype: float64

Columns:
['sender', 'receiver', 'date', 'subject', 'body', 'label', 'urls']

In [12]:
#dataset size and characteristics
for name, df in datasets.items():

    if "text_combined" in df.columns:
        text_col = "text_combined"
    else:
        text_col = "body"

    text_lengths = df[text_col].fillna("").astype(str).str.len()

    print("\n" + "=" * 70)
    print(name)

    print("Average text length :", round(text_lengths.mean(), 2))
    print("Median text length  :", round(text_lengths.median(), 2))
    print("Minimum text length :", text_lengths.min())
    print("Maximum text length :", text_lengths.max())

    print("Empty messages      :", (text_lengths == 0).sum())

======================================================================
CEAS_08.csv
Average text length : 1571.08
Median text length  : 570.0
Minimum text length : 14
Maximum text length : 143996
Empty messages      : 0

======================================================================
Enron.csv
Average text length : 1487.82
Median text length  : 706.0
Minimum text length : 1
Maximum text length : 230120
Empty messages      : 0

======================================================================
Ling.csv
Average text length : 3223.23
Median text length  : 2027.0
Minimum text length : 18
Maximum text length : 28650
Empty messages      : 0

======================================================================
Nazario.csv
Average text length : 4730.03
Median text length  : 720.0
Minimum text length : 1
Maximum text length : 4599644
Empty messages      : 0

======================================================================
Nigerian_Fraud.csv
Average text length : 2644.38
Median text length  : 2547.0
Minimum text length : 2
Maximum text length : 124969
Empty messages      : 0

======================================================================
phishing_email.csv
Average text length : 1288.75
Median text length  : 558.0
Minimum text length : 1
Maximum text length : 4279526
Empty messages      : 0

======================================================================
SpamAssasin.csv
Average text length : 2406.5
Median text length  : 1084.0
Minimum text length : 0
Maximum text length : 299201
Empty messages      : 1